# Pre-push hooks configuration for resume-as-code
# Heavy operations that take longer but ensure code quality before pushing

repos:
  # Build validation (ensure build process works)
  - repo: local
    hooks:
      - id: build-validation
        name: Build validation
        entry: make
        args: ['build']
        language: system
        files: \.(js|json|html|css|md)$
        pass_filenames: false

  # Unit tests validation
  - repo: local
    hooks:
      - id: unit-tests
        name: Run unit tests
        entry: make
        args: ['test-unit']
        language: system
        files: \.(js|json|html)$
        pass_filenames: false

  # Fast smoke tests (not full E2E suite)
  - repo: local
    hooks:
      - id: smoke-tests
        name: Run smoke tests
        entry: make
        args: ['test-fast']
        language: system
        files: \.(js|json|html|css)$
        pass_filenames: false

  # Docker image validation (ensure Dockerfile builds)
  - repo: local
    hooks:
      - id: docker-build-test
        name: Docker build validation
        entry: docker
        args: ['build', '-t', 'resume-test', '.']
        language: system
        files: Dockerfile|docker/.*|package\.json$
        pass_filenames: false
