# 🎯 NETLIFY CONFIGURATION - OPTIMIZED FOR BUILD MINUTES CONSERVATION
#
# Strategy:
# - 🚀 GitHub Pages: Production builds (unlimited)
# - 📱 Netlify: PR previews only (conserves 300 build minutes/month)
# - 🎯 Benefits: Cost-effective, reliable, consistent artifacts
#
# Build Allocation:
# - Production (main): GitHub Pages ✅
# - PR Previews: Netlify ✅
# - Branch Deploys: DISABLED (saves minutes) ❌
# - Random Pushes: DISABLED (saves minutes) ❌

[build]
  # GitHub Actions handles ALL builds - Netlify just serves static files
  # NO BUILD COMMAND - skip builds entirely

  # Directory to publish (contains HTML + PDF + assets from GitHub Actions)
  publish = "dist"

  # Ignore ALL builds - GitHub Actions handles everything
  ignore = "true"

  # Environment variables (not used since we skip builds)
  [build.environment]
    GITHUB_ACTIONS_BUILD = "true"
    NETLIFY_BUILD_DISABLED = "true"

# Production deployment DISABLED - GitHub Pages handles production
# This saves Netlify build minutes (300/month limit)
[context.production]
  ignore = "true"  # Always skip production builds

  [context.production.environment]
    NODE_ENV = "production"
    GITHUB_PAGES = "true"
    NETLIFY_PRODUCTION_DISABLED = "true"

# Deploy Preview settings (for PRs) - NO BUILDS, just serve files from GitHub Actions
[context.deploy-preview]
  publish = "dist"
  ignore = "true"

  [context.deploy-preview.environment]
    GITHUB_ACTIONS_BUILD = "true"
    NETLIFY_BUILD_DISABLED = "true"

# Branch deploy settings DISABLED - Only PR previews allowed
# This saves build minutes for random branch pushes
[context.branch-deploy]
  ignore = "true"  # Always skip branch deploys
  publish = "dist"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://www.google-analytics.com"

# PDF files with proper headers
[[headers]]
  for = "*.pdf"
  [headers.values]
    Content-Type = "application/pdf"
    Cache-Control = "public, max-age=31536000"

# Static assets caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# HTML files
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Redirects for clean URLs
[[redirects]]
  from = "/resume"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/cv"
  to = "/index.html"
  status = 200

# 404 fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
