---
name: ✅ Quality Gates (Conventional Commits)

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to validate (leave empty to validate current branch)'
        required: false
        type: number

concurrency:
  group: conventional-commits-${{ github.event.pull_request.number || inputs.pr_number || github.ref }}
  cancel-in-progress: true

jobs:
  conventional-commits-check:
    name: Validate Conventional Commits
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          # Fetch full history to check all commits in the PR
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install conventional-commits-parser
        run: |
          npm install -g @commitlint/cli @commitlint/config-conventional

      - name: Create commitlint config  
        run: |
          cat > commitlint.config.cjs << 'EOF'
          module.exports = {
            extends: ['@commitlint/config-conventional'],
            rules: {
              'type-enum': [
                2,
                'always',
                [
                  'feat',     // New features
                  'fix',      // Bug fixes
                  'chore',    // Maintenance, dependencies
                  'docs',     // Documentation
                  'style',    // Code formatting (hidden in changelog)
                  'refactor', // Code refactoring
                  'perf',     // Performance improvements
                  'test',     // Test changes (hidden in changelog)
                  'ci',       // CI/CD changes
                  'build',    // Build system changes
                  'revert'    // Revert commits
                ]
              ],
              'scope-case': [2, 'always', 'lower-case'],
              'subject-case': [2, 'always', 'lower-case'],
              'subject-empty': [2, 'never'],
              'subject-full-stop': [2, 'never', '.'],
              'header-max-length': [2, 'always', 100]
            }
          };
          EOF

      - name: Get PR commits
        id: commits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Handle both pull_request and workflow_dispatch triggers
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            if [ -n "${{ inputs.pr_number }}" ]; then
              echo "🔍 Manual validation for PR #${{ inputs.pr_number }}"
              PR_INFO=$(gh pr view ${{ inputs.pr_number }} --json baseRefOid,headRefOid)
              BASE_SHA=$(echo "$PR_INFO" | jq -r '.baseRefOid')
              HEAD_SHA=$(echo "$PR_INFO" | jq -r '.headRefOid')
            else
              echo "🔍 Manual validation for current branch"
              BASE_SHA="origin/main"
              HEAD_SHA="HEAD"
            fi
          else
            # Regular PR trigger
            BASE_SHA="${{ github.event.pull_request.base.sha }}"
            HEAD_SHA="${{ github.event.pull_request.head.sha }}"
          fi

          echo "🔍 Checking commits from $BASE_SHA to $HEAD_SHA"

          # Get commit messages (excluding merge commits)
          git log --format="%H|%s" $BASE_SHA..$HEAD_SHA --no-merges > commits.txt
          
          # Also exclude any commits that start with "Merge" (additional safety)
          grep -v "^[^|]*|Merge " commits.txt > commits_filtered.txt || true
          mv commits_filtered.txt commits.txt

          echo "📋 Commits to validate:"
          cat commits.txt

          # Count commits
          COMMIT_COUNT=$(wc -l < commits.txt)
          echo "commit_count=$COMMIT_COUNT" >> $GITHUB_OUTPUT

          if [ "$COMMIT_COUNT" -eq 0 ]; then
            echo "⚠️ No commits found to validate"
            echo "has_commits=false" >> $GITHUB_OUTPUT
          else
            echo "has_commits=true" >> $GITHUB_OUTPUT
          fi

      - name: Validate conventional commits
        if: steps.commits.outputs.has_commits == 'true'
        run: |
          echo "🎯 Validating conventional commits format..."

          VALIDATION_FAILED=false
          INVALID_COMMITS=""
          VALID_COMMITS=""
          DETAILED_ERRORS=""

          while IFS='|' read -r hash message; do
            echo ""
            echo "🔍 Checking: $message"

            # Capture detailed error output  
            ERROR_OUTPUT=$(echo "$message" | npx commitlint --config commitlint.config.cjs 2>&1) || COMMIT_FAILED=true

            if [ -z "$COMMIT_FAILED" ]; then
              echo "✅ Valid: $message"
              VALID_COMMITS="$VALID_COMMITS\n- ✅ \`$message\`"
            else
              echo "❌ Invalid: $message"
              echo "📋 Error details: $ERROR_OUTPUT"
              VALIDATION_FAILED=true

              # Extract specific rule violations for AI-friendly messages
              RULE_DETAILS=""
              if echo "$ERROR_OUTPUT" | grep -q "subject-case"; then
                RULE_DETAILS="$RULE_DETAILS\n  🔧 **Rule**: subject-case - Subject must be lowercase\n  📖 **Fix**: Change \`Fix Bug\` to \`fix bug\`\n  🔗 **Reference**: https://commitlint.js.org/#/reference-rules?id=subject-case"
              fi
              if echo "$ERROR_OUTPUT" | grep -q "type-enum"; then
                RULE_DETAILS="$RULE_DETAILS\n  🔧 **Rule**: type-enum - Invalid commit type\n  📖 **Fix**: Use feat|fix|chore|docs|style|refactor|perf|test|ci|build|revert\n  🔗 **Reference**: https://commitlint.js.org/#/reference-rules?id=type-enum"
              fi
              if echo "$ERROR_OUTPUT" | grep -q "subject-empty"; then
                RULE_DETAILS="$RULE_DETAILS\n  🔧 **Rule**: subject-empty - Subject cannot be empty\n  📖 **Fix**: Add description after colon: \`feat: add new feature\`\n  🔗 **Reference**: https://commitlint.js.org/#/reference-rules?id=subject-empty"
              fi
              if echo "$ERROR_OUTPUT" | grep -q "header-max-length"; then
                RULE_DETAILS="$RULE_DETAILS\n  🔧 **Rule**: header-max-length - Header too long (max 100 chars)\n  📖 **Fix**: Shorten commit message to under 100 characters\n  🔗 **Reference**: https://commitlint.js.org/#/reference-rules?id=header-max-length"
              fi

              INVALID_COMMITS="$INVALID_COMMITS\n- ❌ \`$message\`$RULE_DETAILS"
              DETAILED_ERRORS="$DETAILED_ERRORS\n\n**Commit**: \`$message\`\n$RULE_DETAILS"
            fi
            unset COMMIT_FAILED
          done < commits.txt

          echo ""
          echo "📊 Validation Summary:"
          echo "Valid commits: $(echo -e "$VALID_COMMITS" | grep -c '✅' || echo 0)"
          echo "Invalid commits: $(echo -e "$INVALID_COMMITS" | grep -c '❌' || echo 0)"

          # Save detailed errors for PR comment
          {
            echo "DETAILED_ERRORS<<EOF"
            echo -e "$DETAILED_ERRORS"
            echo "EOF"
          } >> $GITHUB_ENV

          # Save results for comment
          {
            echo "VALID_COMMITS<<EOF"
            echo -e "$VALID_COMMITS"
            echo "EOF"
          } >> $GITHUB_ENV

          {
            echo "INVALID_COMMITS<<EOF"
            echo -e "$INVALID_COMMITS"
            echo "EOF"
          } >> $GITHUB_ENV

          if [ "$VALIDATION_FAILED" = true ]; then
            echo "validation_failed=true" >> $GITHUB_ENV
            echo ""
            echo "❌ CONVENTIONAL COMMITS VALIDATION FAILED"
            echo "Please fix the invalid commit messages above."
            echo ""
            echo "Valid formats:"
            echo "  feat: add new feature"
            echo "  fix: resolve bug"
            echo "  chore(deps): bump package version"
            echo "  docs: update documentation"
            echo ""
            exit 1
          else
            echo "validation_failed=false" >> $GITHUB_ENV
            echo "✅ All commits follow conventional commits format!"
          fi

      - name: Add PR comment with validation results
        if: always() && steps.commits.outputs.has_commits == 'true'
        uses: actions/github-script@v7
        continue-on-error: true
        env:
          VALIDATION_FAILED: ${{ env.validation_failed }}
          VALID_COMMITS: ${{ env.VALID_COMMITS }}
          INVALID_COMMITS: ${{ env.INVALID_COMMITS }}
          COMMIT_COUNT: ${{ steps.commits.outputs.commit_count }}
        with:
          script: |
            // Handle both pull_request and workflow_dispatch events
            let prNumber;
            if (context.eventName === 'workflow_dispatch') {
              prNumber = ${{ inputs.pr_number || 'null' }};
              if (!prNumber) {
                console.log('⚠️ No PR number specified for workflow_dispatch, skipping PR comment');
                return;
              }
            } else {
              prNumber = context.payload.pull_request.number;
            }
            const validationFailed = process.env.VALIDATION_FAILED === 'true';
            const validCommits = process.env.VALID_COMMITS || '';
            const invalidCommits = process.env.INVALID_COMMITS || '';
            const commitCount = process.env.COMMIT_COUNT || '0';

            const status = validationFailed ? '❌ FAILED' : '✅ PASSED';
            const statusEmoji = validationFailed ? '❌' : '✅';

            let commentBody = `## ${statusEmoji} Conventional Commits Validation

            **Status**: ${status}
            **Commits Checked**: ${commitCount}

            `;

            if (validationFailed) {
              const detailedErrors = process.env.DETAILED_ERRORS || '';

              commentBody += `### ❌ Invalid Commits

            The following commits do NOT follow conventional commits format:
            ${invalidCommits}

            ### 🤖 AI-Friendly Error Details

            ${detailedErrors}

            ### 📋 Required Format

            All commits must follow [Conventional Commits](https://www.conventionalcommits.org/) specification:

            \`\`\`
            <type>(<scope>): <description>
            \`\`\`

            **Valid types**: \`feat\`, \`fix\`, \`chore\`, \`docs\`, \`style\`, \`refactor\`, \`perf\`, \`test\`, \`ci\`, \`build\`, \`revert\`

            **Examples** (note lowercase subjects):
            - \`feat: add new resume section for certifications\`
            - \`fix: resolve qr code url mismatch in preview environments\`
            - \`chore(deps): bump playwright from 1.40.0 to 1.41.0\`
            - \`docs: update api documentation\`

            ### 🔧 Quick Fix Commands

            **Option 1: Amend last commit**
            \`\`\`bash
            git commit --amend -m "feat: your description here (lowercase)"
            git push --force-with-lease
            \`\`\`

            **Option 2: Interactive rebase for multiple commits**
            \`\`\`bash
            git rebase -i HEAD~2  # Adjust number for commits to fix
            # Change 'pick' to 'reword' for commits to fix
            # Save and edit each commit message
            git push --force-with-lease
            \`\`\`

            **Option 3: Squash all commits into one**
            \`\`\`bash
            git reset --soft HEAD~2  # Adjust number for commits to squash
            git commit -m "feat: descriptive commit message here"
            git push --force-with-lease
            \`\`\`

            ### 📚 Documentation Links

            - 📖 [Conventional Commits Specification](https://www.conventionalcommits.org/)
            - 🔧 [Commitlint Rules Reference](https://commitlint.js.org/#/reference-rules)
            - 🎯 [Project CLAUDE.md Guidelines](https://github.com/rafilkmp3/resume-as-code/blob/main/CLAUDE.md#-conventional-commits-implementation)

            `;
            } else {
              commentBody += `### ✅ All Commits Valid

            All commits in this PR follow conventional commits format:
            ${validCommits}

            **Great job!** 🎉 Your commits are properly formatted and will:
            - Generate accurate changelogs
            - Trigger appropriate version bumps
            - Create organized GitHub releases

            ### 📊 Workflow Details
            🔗 [View Complete Workflow Run](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})

            `;
            }

            if (validCommits && validationFailed) {
              commentBody += `### ✅ Valid Commits
            ${validCommits}

            `;
            }

            commentBody += `---
            *This check ensures all commits follow [Conventional Commits](https://www.conventionalcommits.org/) for automated versioning and changelog generation.*`;

            // Check if we already have a conventional commits comment
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
            });

            // Find all previous conventional commits validation comments
            const conventionalCommitsComments = comments.data.filter(comment =>
              comment.user.login === 'github-actions[bot]' &&
              (comment.body.includes('Conventional Commits Validation') || comment.body.includes('conventional-commits-validation-'))
            );

            console.log(`🔍 Found ${conventionalCommitsComments.length} previous conventional commits validation comments`);

            // Hide/minimize ALL previous conventional commits comments (Atlantis behavior)
            let hiddenCount = 0;
            for (const oldComment of conventionalCommitsComments) {
              try {
                // Add "outdated" marker to hide previous comments
                const outdatedBody = `<details>\n<summary>🔒 <strong>Outdated Validation Results</strong> - Click to expand</summary>\n\n${oldComment.body}\n\n---\n*⚠️ This validation report has been superseded by a newer analysis.*\n</details>`;
                
                await github.rest.issues.updateComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  comment_id: oldComment.id,
                  body: outdatedBody,
                });
                hiddenCount++;
              } catch (error) {
                console.log(`⚠️ Could not minimize validation comment ${oldComment.id}: ${error.message}`);
              }
            }

            console.log(`🔒 Minimized ${hiddenCount} previous conventional commits comments (Atlantis-style)`);

            // Add unique comment identifier for atlantis-style management
            commentBody += `\n<!-- conventional-commits-validation-${Date.now()} -->`;

            // Always create fresh comment (never update existing)
            try {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: commentBody,
              });
              
              console.log(`✅ Posted fresh conventional commits validation to PR #${prNumber} (${hiddenCount} old comments minimized)`);
              console.log(`🎯 Atlantis-style management: Only latest validation visible, previous comments collapsed`);
            } catch (error) {
              if (error.message.includes('Resource not accessible by integration')) {
                console.log(`⚠️ Cannot comment on Dependabot PR #${prNumber}: GitHub Actions bot lacks permissions`);
                console.log(`✅ Validation completed successfully - commits are ${validationFailed ? 'INVALID' : 'VALID'}`);
                console.log(`🤖 Dependabot PRs have restricted comment permissions for security`);
                
                // Don't fail the workflow for Dependabot permission issues
                if (!validationFailed) {
                  console.log(`🎉 Dependabot PR #${prNumber} has valid conventional commits - workflow passes despite comment restriction`);
                }
              } else {
                console.error(`❌ Failed to post comment: ${error.message}`);
                throw error; // Re-throw non-permission errors
              }
            }

      - name: Generate step summary
        if: always()
        run: |
          if [ "${{ steps.commits.outputs.has_commits }}" = "false" ]; then
            echo "## ⚠️ No commits to validate" >> $GITHUB_STEP_SUMMARY
            echo "This PR has no new commits to validate." >> $GITHUB_STEP_SUMMARY
            exit 0
          fi

          if [ "${{ env.validation_failed }}" = "true" ]; then
            echo "## ❌ Conventional Commits Validation Failed" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Invalid commits found**: This PR contains commits that do not follow conventional commits format." >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### 🤖 AI-Friendly Error Details" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo -e "${{ env.DETAILED_ERRORS }}" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### 🔧 Quick Fix Commands" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Most common fix (lowercase subject)**:" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
            echo "git commit --amend -m \"feat: your description here (lowercase)\"" >> $GITHUB_STEP_SUMMARY
            echo "git push --force-with-lease" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### 📚 References" >> $GITHUB_STEP_SUMMARY
            echo "- [Conventional Commits](https://www.conventionalcommits.org/)" >> $GITHUB_STEP_SUMMARY
            echo "- [Commitlint Rules](https://commitlint.js.org/#/reference-rules)" >> $GITHUB_STEP_SUMMARY
          else
            echo "## ✅ Conventional Commits Validation Passed" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**All commits validated**: All ${{ steps.commits.outputs.commit_count }} commits follow conventional commits format." >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### Benefits" >> $GITHUB_STEP_SUMMARY
            echo "- ✅ Automated version bumping" >> $GITHUB_STEP_SUMMARY
            echo "- ✅ Generated changelogs" >> $GITHUB_STEP_SUMMARY
            echo "- ✅ Organized GitHub releases" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Final validation status
        if: always() && steps.commits.outputs.has_commits == 'true'
        run: |
          if [ "${{ env.validation_failed }}" = "true" ]; then
            echo "❌ Conventional commits validation failed - workflow will exit with error"
            exit 1
          else
            echo "✅ All conventional commits validation passed successfully"
            # Check if this is a Dependabot PR by looking at the actor
            if [[ "${{ github.actor }}" == "dependabot[bot]" ]]; then
              echo "🤖 Dependabot PR detected - comment posting may be restricted but validation succeeded"
              echo "🎉 Dependabot commits follow conventional format correctly"
            fi
            exit 0
          fi
