---
name: Conventional Commits Check

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

concurrency:
  group: conventional-commits-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  conventional-commits-check:
    name: Validate Conventional Commits
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetch full history to check all commits in the PR
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install conventional-commits-parser
        run: |
          npm install -g @commitlint/cli @commitlint/config-conventional

      - name: Create commitlint config
        run: |
          cat > commitlint.config.js << 'EOF'
          module.exports = {
            extends: ['@commitlint/config-conventional'],
            rules: {
              'type-enum': [
                2,
                'always',
                [
                  'feat',     // New features
                  'fix',      // Bug fixes
                  'chore',    // Maintenance, dependencies
                  'docs',     // Documentation
                  'style',    // Code formatting (hidden in changelog)
                  'refactor', // Code refactoring
                  'perf',     // Performance improvements
                  'test',     // Test changes (hidden in changelog)
                  'ci',       // CI/CD changes
                  'build',    // Build system changes
                  'revert'    // Revert commits
                ]
              ],
              'scope-case': [2, 'always', 'lower-case'],
              'subject-case': [2, 'always', 'lower-case'],
              'subject-empty': [2, 'never'],
              'subject-full-stop': [2, 'never', '.'],
              'header-max-length': [2, 'always', 100]
            }
          };
          EOF

      - name: Get PR commits
        id: commits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get all commit messages in this PR
          BASE_SHA="${{ github.event.pull_request.base.sha }}"
          HEAD_SHA="${{ github.event.pull_request.head.sha }}"

          echo "🔍 Checking commits from $BASE_SHA to $HEAD_SHA"

          # Get commit messages (excluding merge commits)
          git log --format="%H|%s" $BASE_SHA..$HEAD_SHA --no-merges > commits.txt

          echo "📋 Commits to validate:"
          cat commits.txt

          # Count commits
          COMMIT_COUNT=$(wc -l < commits.txt)
          echo "commit_count=$COMMIT_COUNT" >> $GITHUB_OUTPUT

          if [ "$COMMIT_COUNT" -eq 0 ]; then
            echo "⚠️ No commits found to validate"
            echo "has_commits=false" >> $GITHUB_OUTPUT
          else
            echo "has_commits=true" >> $GITHUB_OUTPUT
          fi

      - name: Validate conventional commits
        if: steps.commits.outputs.has_commits == 'true'
        run: |
          echo "🎯 Validating conventional commits format..."

          VALIDATION_FAILED=false
          INVALID_COMMITS=""
          VALID_COMMITS=""

          while IFS='|' read -r hash message; do
            echo ""
            echo "🔍 Checking: $message"

            if echo "$message" | npx commitlint --config commitlint.config.js; then
              echo "✅ Valid: $message"
              VALID_COMMITS="$VALID_COMMITS\n- ✅ \`$message\`"
            else
              echo "❌ Invalid: $message"
              VALIDATION_FAILED=true
              INVALID_COMMITS="$INVALID_COMMITS\n- ❌ \`$message\`"
            fi
          done < commits.txt

          echo ""
          echo "📊 Validation Summary:"
          echo "Valid commits: $(echo -e "$VALID_COMMITS" | grep -c '✅' || echo 0)"
          echo "Invalid commits: $(echo -e "$INVALID_COMMITS" | grep -c '❌' || echo 0)"

          # Save results for comment
          {
            echo "VALID_COMMITS<<EOF"
            echo -e "$VALID_COMMITS"
            echo "EOF"
          } >> $GITHUB_ENV

          {
            echo "INVALID_COMMITS<<EOF"
            echo -e "$INVALID_COMMITS"
            echo "EOF"
          } >> $GITHUB_ENV

          if [ "$VALIDATION_FAILED" = true ]; then
            echo "validation_failed=true" >> $GITHUB_ENV
            echo ""
            echo "❌ CONVENTIONAL COMMITS VALIDATION FAILED"
            echo "Please fix the invalid commit messages above."
            echo ""
            echo "Valid formats:"
            echo "  feat: add new feature"
            echo "  fix: resolve bug"
            echo "  chore(deps): bump package version"
            echo "  docs: update documentation"
            echo ""
            exit 1
          else
            echo "validation_failed=false" >> $GITHUB_ENV
            echo "✅ All commits follow conventional commits format!"
          fi

      - name: Add PR comment with validation results
        if: always() && steps.commits.outputs.has_commits == 'true'
        uses: actions/github-script@v7
        env:
          VALIDATION_FAILED: ${{ env.validation_failed }}
          VALID_COMMITS: ${{ env.VALID_COMMITS }}
          INVALID_COMMITS: ${{ env.INVALID_COMMITS }}
          COMMIT_COUNT: ${{ steps.commits.outputs.commit_count }}
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const validationFailed = process.env.VALIDATION_FAILED === 'true';
            const validCommits = process.env.VALID_COMMITS || '';
            const invalidCommits = process.env.INVALID_COMMITS || '';
            const commitCount = process.env.COMMIT_COUNT || '0';

            const status = validationFailed ? '❌ FAILED' : '✅ PASSED';
            const statusEmoji = validationFailed ? '❌' : '✅';

            let commentBody = `## ${statusEmoji} Conventional Commits Validation

            **Status**: ${status}
            **Commits Checked**: ${commitCount}

            `;

            if (validationFailed) {
              commentBody += `### ❌ Invalid Commits

            The following commits do NOT follow conventional commits format:
            ${invalidCommits}

            ### 📋 Required Format

            All commits must follow [Conventional Commits](https://www.conventionalcommits.org/) specification:

            \`\`\`
            <type>(<scope>): <description>
            \`\`\`

            **Valid types**: \`feat\`, \`fix\`, \`chore\`, \`docs\`, \`style\`, \`refactor\`, \`perf\`, \`test\`, \`ci\`, \`build\`, \`revert\`

            **Examples**:
            - \`feat: add new resume section for certifications\`
            - \`fix: resolve QR code URL mismatch in preview environments\`
            - \`chore(deps): bump playwright from 1.40.0 to 1.41.0\`
            - \`docs: update API documentation\`

            ### 🔧 How to Fix

            1. **Rewrite commit messages** using \`git rebase -i\` to edit commit messages
            2. **Or squash commits** into properly formatted conventional commits
            3. **Force push** the corrected commits

            \`\`\`bash
            # Example: Rewrite last commit message
            git commit --amend -m "feat: describe your feature properly"
            git push --force-with-lease
            \`\`\`

            `;
            } else {
              commentBody += `### ✅ All Commits Valid

            All commits in this PR follow conventional commits format:
            ${validCommits}

            **Great job!** 🎉 Your commits are properly formatted and will:
            - Generate accurate changelogs
            - Trigger appropriate version bumps
            - Create organized GitHub releases

            `;
            }

            if (validCommits && validationFailed) {
              commentBody += `### ✅ Valid Commits
            ${validCommits}

            `;
            }

            commentBody += `---
            *This check ensures all commits follow [Conventional Commits](https://www.conventionalcommits.org/) for automated versioning and changelog generation.*`;

            // Check if we already have a conventional commits comment
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
            });

            const existingComment = comments.data.find(comment =>
              comment.user.login === 'github-actions[bot]' &&
              comment.body.includes('Conventional Commits Validation')
            );

            if (existingComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: existingComment.id,
                body: commentBody,
              });
              console.log('Updated existing conventional commits comment');
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: commentBody,
              });
              console.log('Created new conventional commits comment');
            }

      - name: Generate step summary
        if: always()
        run: |
          if [ "${{ steps.commits.outputs.has_commits }}" = "false" ]; then
            echo "## ⚠️ No commits to validate" >> $GITHUB_STEP_SUMMARY
            echo "This PR has no new commits to validate." >> $GITHUB_STEP_SUMMARY
            exit 0
          fi

          if [ "${{ env.validation_failed }}" = "true" ]; then
            echo "## ❌ Conventional Commits Validation Failed" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Invalid commits found**: This PR contains commits that do not follow conventional commits format." >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### Required Action" >> $GITHUB_STEP_SUMMARY
            echo "1. Fix commit messages using \`git rebase -i\` or \`git commit --amend\`" >> $GITHUB_STEP_SUMMARY
            echo "2. Force push the corrected commits" >> $GITHUB_STEP_SUMMARY
            echo "3. Re-run this check" >> $GITHUB_STEP_SUMMARY
          else
            echo "## ✅ Conventional Commits Validation Passed" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**All commits validated**: All ${{ steps.commits.outputs.commit_count }} commits follow conventional commits format." >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### Benefits" >> $GITHUB_STEP_SUMMARY
            echo "- ✅ Automated version bumping" >> $GITHUB_STEP_SUMMARY
            echo "- ✅ Generated changelogs" >> $GITHUB_STEP_SUMMARY
            echo "- ✅ Organized GitHub releases" >> $GITHUB_STEP_SUMMARY
          fi
