on:
  push:
    branches:
      - main
name: release-please

permissions:
  contents: write
  pull-requests: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          target-branch: main
          pull-request-title-pattern: "chore(release): ${version}"
          release-as: 1.2.2
