---
name: 🧪 Test Job Dependencies

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  first-job:
    name: First Job
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Test release-please action
        uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json
          token: ${{ secrets.GITHUB_TOKEN }}

  second-job:
    name: Second Job  
    needs: first-job
    if: needs.first-job.outputs.release_created
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        run: echo "Second job running"