---
name: 🧪 Minimal Test Workflow

on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: Minimal Test
    runs-on: ubuntu-latest
    steps:
      - name: Echo test
        run: echo "Hello world"