---
name: 🧪 Test Release Simple

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  test-release:
    name: Test Release Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Test release-please action
        uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Test step
        run: echo "Testing release-like workflow"