---
name: 🧪 Test Release Simple

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  test-release:
    name: Test Release Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Test step
        run: echo "Testing release-like workflow"